# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connection_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


try:
    from PySide2 import QtGui
    from PySide2 import QtCore
    from PySide2 import QtWidgets
except ImportError:
    from PyQt5 import QtGui, QtCore, QtWidgets


class Ui_ConnectionDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(459, 130)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelServer = QtWidgets.QLabel(Dialog)
        self.labelServer.setMinimumSize(QtCore.QSize(50, 0))
        self.labelServer.setObjectName("labelServer")
        self.horizontalLayout.addWidget(self.labelServer)
        self.lineEditServer = QtWidgets.QLineEdit(Dialog)
        self.lineEditServer.setObjectName("lineEditServer")
        self.horizontalLayout.addWidget(self.lineEditServer)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelEmail = QtWidgets.QLabel(Dialog)
        self.labelEmail.setMinimumSize(QtCore.QSize(50, 0))
        self.labelEmail.setObjectName("labelEmail")
        self.horizontalLayout_2.addWidget(self.labelEmail)
        self.lineEditEmail = QtWidgets.QLineEdit(Dialog)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.horizontalLayout_2.addWidget(self.lineEditEmail)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEditPassword = QtWidgets.QLineEdit(Dialog)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.horizontalLayout_3.addWidget(self.lineEditPassword)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelServer.setText(_translate("Dialog", "Server"))
        self.labelEmail.setText(_translate("Dialog", "Email"))
        self.label_3.setText(_translate("Dialog", "Password"))
