# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


try:
    from PySide2 import QtGui
    from PySide2 import QtCore
    from PySide2 import QtWidgets
except ImportError:
    from PyQt5 import QtGui, QtCore, QtWidgets


class Ui_DownloadDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(590, 400)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelWorkingDirectory = QtWidgets.QLabel(Dialog)
        self.labelWorkingDirectory.setObjectName("labelWorkingDirectory")
        self.horizontalLayout.addWidget(self.labelWorkingDirectory)
        self.lineEditWorkingDirectory = QtWidgets.QLineEdit(Dialog)
        self.lineEditWorkingDirectory.setObjectName("lineEditWorkingDirectory")
        self.horizontalLayout.addWidget(self.lineEditWorkingDirectory)
        self.pushButtonSelectWorkingDir = QtWidgets.QPushButton(Dialog)
        self.pushButtonSelectWorkingDir.setObjectName("pushButtonSelectWorkingDir")
        self.horizontalLayout.addWidget(self.pushButtonSelectWorkingDir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBoxSkipExisting = QtWidgets.QCheckBox(Dialog)
        self.checkBoxSkipExisting.setChecked(True)
        self.checkBoxSkipExisting.setObjectName("checkBoxSkipExisting")
        self.horizontalLayout_2.addWidget(self.checkBoxSkipExisting)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBoxExtractZip = QtWidgets.QCheckBox(Dialog)
        self.checkBoxExtractZip.setChecked(True)
        self.checkBoxExtractZip.setObjectName("checkBoxExtractZip")
        self.horizontalLayout_3.addWidget(self.checkBoxExtractZip)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButtonDownload = QtWidgets.QPushButton(Dialog)
        self.pushButtonDownload.setDefault(True)
        self.pushButtonDownload.setObjectName("pushButtonDownload")
        self.horizontalLayout_4.addWidget(self.pushButtonDownload)
        self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
        self.pushButtonCancel.setAutoDefault(False)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_4.addWidget(self.pushButtonCancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Download Files"))
        self.labelWorkingDirectory.setText(_translate("Dialog", "Working Directory:"))
        self.pushButtonSelectWorkingDir.setText(_translate("Dialog", "Select"))
        self.checkBoxSkipExisting.setText(_translate("Dialog", "Skip Existing Files"))
        self.checkBoxExtractZip.setText(_translate("Dialog", "Extract Zip Files"))
        self.pushButtonDownload.setText(_translate("Dialog", "Download"))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel"))
